# Generated by Django 3.1.7 on 2022-02-08 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, null=True)),
                ('describe', models.TextField()),
                ('user_name', models.CharField(blank=True, max_length=20, null=True)),
                ('app_date_tiem', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=264)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pic')),
                ('description', models.TextField(blank=True)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('website', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
